<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="John Johnson" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project 1: Exploratory Data Analysis</title>
    <meta name="generator" content="Hugo 0.83.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project1/">Project 1: Exploratory Data Analysis</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="data-wrangling-and-data-exploration" class="section level2">
<h2>Data Wrangling and Data Exploration</h2>
<div id="instructions" class="section level3">
<h3>Instructions</h3>
<p>A knitted R Markdown document (ideally HTML) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on the due date. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document).</p>
<p>The text of the document should provide a narrative structure around your code/output. All results presented must have corresponding code. Any answers/results/plots etc. given without the corresponding R code that generated the result will not be considered. Furthermore, all code contained in your final project document must work correctly (knit early, knit often)! Please do not include any extraneous code or code which produces error messages. (Code that produces warnings is acceptable, as long as you understand what the warnings mean!)</p>
</div>
<div id="find-data" class="section level3">
<h3>Find data:</h3>
<p>Find two (!) datasets with one variable in common (e.g., dates, times, states, counties, countries, sports players), both with at least 50 observations (i.e., rows) in each. Please think very carefully about whether it makes sense to combine your datasets! If you find one dataset with 50 patients and it has their age, and you find another dataset with 50 <em>different</em> patients that has their ages, it makes no sense to join them based on age (you would just be pairing up random people of the same age).</p>
<p>When combined, the resulting/final dataset must have <strong>at least 4 different variables (at least 3 numeric) in addition to the common variable</strong> (i.e., five variables total).</p>
<p>You can have as many variables as you would like! If you found two datasets that you like but they don’t have enough variables, find a third dataset with the same common variable and join all three.</p>
</div>
<div id="guidelines" class="section level3">
<h3>Guidelines</h3>
<ol style="list-style-type: decimal">
<li><p>If the datasets are not tidy, you will need to reshape them so that every observation has its own row and every variable its own column. If the datasets are both already tidy, you will make them untidy with <code>pivot_wider()/spread()</code> and then tidy them again with <code>pivot_longer/gather()</code> to demonstrate your use of the functions. It’s fine to wait until you have your descriptives to use these functions (e.g., you might want to pivot_wider() to rearrange the data to make your descriptive statistics easier to look at); it’s fine long as you use them at least once!</p>
<ul>
<li><p>Depending on your datasets, it might be a good idea to do this before joining. For example, if you have a dataset you like with multiple measurements per year, but you want to join by year, you could average over your numeric variables to get means/year, do counts for your categoricals to get a counts/year, etc.</p></li>
<li><p>If your data sets are already tidy, demonstrate the use of <code>pivot_longer()/gather()</code> and <code>pivot_wider()/spread()</code> on all or part of your data at some point in this document (e.g., after you have generated summary statistics in part 3, make a table of them wide instead of long).</p></li>
</ul></li>
<li><p>Join your 2+ separate data sources into a single dataset based on a common ID variable! If you can’t find a good pair datasets to join, you may split one main dataset into two different datasets with a common ID variable in each, and then join them back together based on that common ID, but this is obviously less than ideal.</p>
<ul>
<li>You will document the type of join that you do (left/right/inner/full), including a discussion of how many observations were in each dataset, which observations in each dataset were dropped (if any) and why you chose this particular join.</li>
</ul></li>
<li><p>Create summary statistics</p>
<ul>
<li><p>Use <em>all six</em> core <code>dplyr</code> functions (<code>filter, select, arrange, group_by, mutate, summarize</code>) to manipulate and explore your dataset. For mutate, create a new variable that is a function of at least one other variable, preferably using a dplyr vector function (see dplyr cheatsheet). It’s totally fine to use the <code>_if</code>, <code>_at</code>, <code>_all</code> versions of mutate/summarize instead (indeed, it is encouraged if you have lots of variables)</p></li>
<li><p>Create summary statistics (<code>mean, sd, var, n, quantile, min, max, n_distinct, cor</code>, etc) for each of your numeric variables both overall and after grouping by one of your categorical variables (either together or one-at-a-time; if you have two categorical variables, try to include at least one statistic based on a grouping of two categorical variables simultaneously). If you do not have any categorical variables, create one using mutate (e.g., with <code>case_when</code> or <code>ifelse</code>) to satisfy the <code>group_by</code> requirements above. Ideally, you will find a way to show these summary statistics in an easy-to-read table (e.g., by reshaping). (You might explore the kable package for making pretty tables!) If you have lots of numeric variables (e.g., 10+), or your categorical variables have too many categories, just pick a few (either numeric variables or categories of a categorical variable) and summarize based on those. It would be a good idea to show a correlation matrix for your numeric variables (you will need it to make one of your plots).</p></li>
</ul></li>
<li><p>Make visualizations (three plots)</p>
<ul>
<li>Make a correlation heatmap of your numeric variables</li>
<li>Create at least two additional plots of your choice with ggplot that highlight some of the more interesting features of your data.</li>
<li>Each plot (besides the heatmap) should have at least three variables mapped to separate aesthetics</li>
<li>Each should use different geoms (e.g., don’t do two geom_bars)</li>
<li>At least one plot should include <code>stat="summary"</code></li>
<li>Each plot should include a supporting paragraph describing the relationships that are being visualized and any trends that are apparent
<ul>
<li>It is fine to include more, but limit yourself to 4. Plots should avoid being redundant! Four bad plots will get a lower grade than two good plots, all else being equal.</li>
</ul></li>
<li>Make them pretty! Use correct labels, etc.</li>
</ul></li>
<li><p>Perform k-means/PAM clustering or PCA on (at least) your numeric variables.</p>
<ul>
<li><p>Include all steps as we discuss in class, including a visualization.</p></li>
<li><p>If you don’t have at least 3 numeric variables, or you want to cluster based on categorical variables too, convert them to factors in R, generate Gower’s dissimilarity matrix on the data, and do PAM clustering on the dissimilarities.</p></li>
<li><p>Show how you chose the final number of clusters/principal components</p></li>
<li><p>Interpret the final clusters/principal components</p></li>
<li><p>For every step, document what your code does (in words) and what you see in the data!</p></li>
</ul></li>
</ol>
<P style="page-break-before: always">
<div style="page-break-after: always;"></div>
</div>
<div id="rubric" class="section level3">
<h3>Rubric</h3>
<p>Prerequisite: Finding appropriate data from at least two sources per the instructions above: Failure to do this will result in a 0! You will submit a .Rmd file and a knitted document (html/pdf).</p>
<div id="introduction-5-pts" class="section level4">
<h4>0. Introduction (5 pts)</h4>
<ul>
<li>Write a narrative introductory paragraph or two describing the datasets you have chosen, the variables they contain, how they were acquired, and why they are interesting to you. Expand on potential associations you may expect, if any.</li>
</ul>
<pre class="r"><code>data(us_rent_income)
data(USArrests)</code></pre>
<p><em>For my first data set I chose “us_rent_income” - a dataset with 5 different variables. The variables are the FIP state identifier, the name of the state, the median yearly income and median monthly rent, the estimated value, and the 90% margin of error (moe) value. The second dataset I chose was ‘USArrests" - a dataset with 5 different variables. The variables are the name of the state, the number of murder arrests per 100,000 people, the number of assaults arrests per 100,000 people, percent of the urban population, and the number of rape arrests per 100,000 people. The “USArrests” dataset was acquired from the ’datasets’ package in R Studio and the “us_rent_income” dataset was acquired from the ‘tidyr’ package in R Studio.</em></p>
<p><em>These two variables are interesting to me because I want to see if their is any relationship between a state’s income and/or rent and the incidence of crime in each of these states. I want to analyze this relationship in hopes of better understanding how rates of arrests correlate with income/rent levels. One relationship I expect to find is that lower levels of income will be correlated with higher rates of arrests across the board. I expect this because low income levels can lead people to engage in dangerous behaviors/acts in order to meet their needs.</em></p>
</div>
<div id="tidying-rearranging-widelong-10-pts" class="section level4">
<h4>1. Tidying: Rearranging Wide/Long (10 pts)</h4>
<ul>
<li>Tidy the datasets (using the <code>tidyr</code> functions <code>pivot_longer</code>/<code>gather</code> and/or <code>pivot_wider</code>/<code>spread</code>)</li>
<li>If you data sets are already tidy, be sure to use those functions somewhere else in your project (e.g., for rearranging summary statistics)</li>
<li>Document the process (describe in words what was done)</li>
</ul>
<pre class="r"><code>library(tidyr)
us_rent_income2 &lt;- pivot_wider(us_rent_income, names_from = &quot;variable&quot;, 
    values_from = &quot;estimate&quot;)

USArrests2 &lt;- tibble::rownames_to_column(USArrests, &quot;State&quot;)

(USArrests2)</code></pre>
<pre><code>##          State Murder Assault UrbanPop Rape
## 1      Alabama   13.2     236       58 21.2
## 2       Alaska   10.0     263       48 44.5
## 3      Arizona    8.1     294       80 31.0
## 4     Arkansas    8.8     190       50 19.5
## 5   California    9.0     276       91 40.6
## 6     Colorado    7.9     204       78 38.7
## 7  Connecticut    3.3     110       77 11.1
## 8     Delaware    5.9     238       72 15.8
## 9      Florida   15.4     335       80 31.9
## 10     Georgia   17.4     211       60 25.8
## 11      Hawaii    5.3      46       83 20.2
## 12       Idaho    2.6     120       54 14.2
## 13    Illinois   10.4     249       83 24.0
## 14     Indiana    7.2     113       65 21.0
## 15        Iowa    2.2      56       57 11.3
## 16      Kansas    6.0     115       66 18.0
## 17    Kentucky    9.7     109       52 16.3
## 18   Louisiana   15.4     249       66 22.2
## 19       Maine    2.1      83       51  7.8
## 20    Maryland   11.3     300       67 27.8
##  [ reached &#39;max&#39; / getOption(&quot;max.print&quot;) -- omitted 30 rows ]</code></pre>
<p><em>The “USArrests” dataset was already Tidy so I did not have to wrangle/pivot_longer/wider the dataset. I did however have to convert the row names - which were just the names of the states - into it’s own column called “States”. In the “us_rent_income” dataset, I did need to pivot_wider the ‘variables’ column to make ‘income’ and ‘rent’ into their own columns with each respective numeric estimate within each column. </em></p>
</div>
<div id="joiningmerging-10-pts" class="section level4">
<h4>2. Joining/Merging (10 pts)</h4>
<ul>
<li>Join your datasets into one using a <code>dplyr</code> join function</li>
<li>If you have multiple observations on the joining variable in either dataset, fix this by collapsing via summarize</li>
<li>Discuss the process in words, including why you chose the join you did</li>
<li>Discuss which cases were dropped, if any, and potential problems with this</li>
</ul>
<pre class="r"><code>library(tidyr)
library(dplyr)
alldata &lt;- us_rent_income2 %&gt;% full_join(USArrests2, by = c(NAME = &quot;State&quot;)) %&gt;% 
    slice(1:16, 19:102)

alldata</code></pre>
<pre><code>## # A tibble: 100 x 9
##    GEOID NAME         moe income  rent Murder Assault UrbanPop  Rape
##    &lt;chr&gt; &lt;chr&gt;      &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;int&gt;    &lt;int&gt; &lt;dbl&gt;
##  1 01    Alabama      136  24476    NA   13.2     236       58  21.2
##  2 01    Alabama        3     NA   747   13.2     236       58  21.2
##  3 02    Alaska       508  32940    NA   10       263       48  44.5
##  4 02    Alaska        13     NA  1200   10       263       48  44.5
##  5 04    Arizona      148  27517    NA    8.1     294       80  31  
##  6 04    Arizona        4     NA   972    8.1     294       80  31  
##  7 05    Arkansas     165  23789    NA    8.8     190       50  19.5
##  8 05    Arkansas       5     NA   709    8.8     190       50  19.5
##  9 06    California   109  29454    NA    9       276       91  40.6
## 10 06    California     3     NA  1358    9       276       91  40.6
## # … with 90 more rows</code></pre>
<p><em>I chose the full join option because I wanted to retain all of the variables in my datasets. Furthermore, I full_joined based on the name of the State - which was the easiest ways to join the two datasets. There were two states in the “us_rent_income” dataset that I had to remove. These were rows containing Puerto Rico and Distric of Columbia. They were removed because there was no corresponding State names in the “USArrests” dataset. One potential problem of this is that you lose these two rent/income amounts - which may skew the data in a particular direction. However, this makes it easier to look at the data because we can better analyze the relationship between the “USArrests” data with the “us_rent_income” data.</em></p>
</div>
<div id="wrangling-40-pts" class="section level4">
<h4>3. Wrangling (40 pts)</h4>
<ul>
<li>Use all six core <code>dplyr</code> functions in the service of generating summary tables/statistics (12 pts)
<ul>
<li>Use mutate at least once to generate a variable that is a function of at least one other variable</li>
</ul></li>
<li>Compute summary statistics for each of your variables using <code>summarize</code> alone and with <code>group_by</code> (if you have more than 10 variables, fine to just focus on 10) (20 pts)
<ul>
<li>Use at least 5 unique functions inside of summarize (e.g., mean, sd)</li>
<li>For at least 2, use summarize after grouping by a categorical variable. Create one by dichotomizing a numeric if necessary</li>
<li>If applicable, at least 1 of these should group by two categorical variables</li>
</ul></li>
<li>Summarize the procedure and discuss all (or the most interesting) results in no more than two paragraphs (8 pts)</li>
</ul>
<pre class="r"><code>alldata2 &lt;- alldata %&gt;% pivot_longer(cols = c(&quot;income&quot;, &quot;rent&quot;), 
    names_to = &quot;Variable&quot;, values_to = &quot;Value&quot;) %&gt;% na.omit()
subdata &lt;- alldata2 %&gt;% group_by(NAME) %&gt;% filter(Variable == 
    &quot;income&quot;) %&gt;% mutate(IM_Rate = Value/Murder) %&gt;% arrange(desc(IM_Rate))
subdata2 &lt;- alldata2 %&gt;% group_by(NAME) %&gt;% filter(Variable == 
    &quot;rent&quot;) %&gt;% mutate(RM_Rate = Value/Murder) %&gt;% arrange(desc(RM_Rate))


alldata2 %&gt;% filter(Variable == &quot;income&quot;) %&gt;% summarize(mean_annual_income = mean(Value))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   mean_annual_income
##                &lt;dbl&gt;
## 1             28908.</code></pre>
<pre class="r"><code>alldata2 %&gt;% filter(Variable == &quot;rent&quot;) %&gt;% summarize(mean_annual_rent = mean(Value * 
    12))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   mean_annual_rent
##              &lt;dbl&gt;
## 1           11181.</code></pre>
<pre class="r"><code>alldata2 %&gt;% group_by(Variable) %&gt;% filter(Variable == &quot;income&quot;) %&gt;% 
    summarize(mean_moe_income = mean(moe))</code></pre>
<pre><code>## # A tibble: 1 x 2
##   Variable mean_moe_income
##   &lt;chr&gt;              &lt;dbl&gt;
## 1 income              177.</code></pre>
<pre class="r"><code>alldata2 %&gt;% group_by(Variable) %&gt;% filter(Variable == &quot;rent&quot;) %&gt;% 
    summarize(mean_moe_rent = mean(moe))</code></pre>
<pre><code>## # A tibble: 1 x 2
##   Variable mean_moe_rent
##   &lt;chr&gt;            &lt;dbl&gt;
## 1 rent              5.38</code></pre>
<pre class="r"><code>alldata2 %&gt;% summarize(n_States = n_distinct(NAME), n_GEOID = n_distinct(GEOID), 
    min_Assault = min(Assault), max_Murder = max(Murder), sd_UrbanPop = sd(UrbanPop), 
    median_Rape = median(Rape))</code></pre>
<pre><code>## # A tibble: 1 x 6
##   n_States n_GEOID min_Assault max_Murder sd_UrbanPop median_Rape
##      &lt;int&gt;   &lt;int&gt;       &lt;int&gt;      &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;
## 1       50      50          45       17.4        14.4        20.1</code></pre>
<pre class="r"><code>subdata %&gt;% select(NAME, Murder, Variable, Value, IM_Rate)</code></pre>
<pre><code>## # A tibble: 50 x 5
## # Groups:   NAME [50]
##    NAME          Murder Variable Value IM_Rate
##    &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;   &lt;dbl&gt;
##  1 North Dakota     0.8 income   32336  40420 
##  2 New Hampshire    2.1 income   33172  15796.
##  3 Iowa             2.2 income   30002  13637.
##  4 Vermont          2.2 income   29351  13341.
##  5 Maine            2.1 income   26841  12781.
##  6 Minnesota        2.7 income   32734  12124.
##  7 Wisconsin        2.6 income   29868  11488.
##  8 Connecticut      3.3 income   35326  10705.
##  9 Idaho            2.6 income   25298   9730 
## 10 Rhode Island     3.4 income   30210   8885.
## # … with 40 more rows</code></pre>
<pre class="r"><code>subdata2 %&gt;% select(NAME, Murder, Variable, Value, RM_Rate)</code></pre>
<pre><code>## # A tibble: 50 x 5
## # Groups:   NAME [50]
##    NAME          Murder Variable Value RM_Rate
##    &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;   &lt;dbl&gt;
##  1 North Dakota     0.8 rent       775    969.
##  2 New Hampshire    2.1 rent      1052    501.
##  3 Vermont          2.2 rent       945    430.
##  4 Maine            2.1 rent       808    385.
##  5 Connecticut      3.3 rent      1123    340.
##  6 Iowa             2.2 rent       740    336.
##  7 Minnesota        2.7 rent       906    336.
##  8 Wisconsin        2.6 rent       813    313.
##  9 Idaho            2.6 rent       792    305.
## 10 Utah             3.2 rent       948    296.
## # … with 40 more rows</code></pre>
<pre class="r"><code>alldata3 &lt;- alldata2 %&gt;% inner_join(subdata)

alldata4 &lt;- alldata2 %&gt;% inner_join(subdata2)</code></pre>
<p><em>For my data I first pivoted_longer mydataset to remove NA’s as this made visualizing/grouping/filtering/etc., much easier to do. I first looked at the mean annual income and mean annual rent across the states - with the mean rent being much lower than I expected of $11,181.36. I then analyzed the Margin of error values (moe) for yearly income estimates (+/- $77.28) and monthly rent estimates (+/- $5.38). This data made sense because the estimates were larger for income and smaller for rent, and because yearly estimates have more margin for error than monthly estimates. Next, I looked at the standard deviation of the Urban Populations across states, the median rape per 100,000 people across states, the minimum number of assaults per 100,000 that occurred in the dataset (45), and the maximum number of murders per 100,000 people that occcured in the dataset (17.4), as well as the unique number of states/unique state identifiers (GEOID).</em></p>
<p><em>Lastly, I took two sets of subdata each containing a new variable. First, I wanted to look at the ratio of annual income to murders per 100,000 people, by state. North Dakota had the highestr Income to murder rate ratio as well as the highest rent to murder rate ratio. This is not all surprising given that North Dakota had the lowest murder rate of 0.8 per 100,000 people. Mississipi on the flip side had the lowest income to murder rate ratio and the lowest rent to murder rate ratio. Low income/rent values in Mississip as well as a relativley higher murder rate made this observation not very surprising. One interesting observation was that most of the states with the highest income/rent murder rate ratio were in the north east (New Hampshire, Vermont, Conneticut) and the upper mid west (North Dakota, Iowa, Minnesota, Wisconsin).</em></p>
</div>
<div id="visualizing-30-pts" class="section level4">
<h4>4. Visualizing (30 pts)</h4>
<ul>
<li><p>Create a correlation heatmap of your numeric variables the way we did in class</p></li>
<li><p>Create two more effective, polished plots with ggplot</p>
<ul>
<li>Each plot should map 3+ variables to aesthetics</li>
<li>Each plot should have a title and clean labeling for all mappings</li>
<li>Change at least one default theme element and color for at least one mapping per plot</li>
<li>For at least one plot, add more tick marks (x, y, or both) than are given by default</li>
<li>For at least one plot, use the stat=“summary” function</li>
<li>Supporting paragraph or two (for each plot) describing the relationships/trends that are apparent</li>
</ul></li>
</ul>
<pre class="r"><code>library(ggplot2)
library(data.table)
require(tibble)


alldata3 %&gt;% select_if(is.numeric) %&gt;% cor %&gt;% as.data.frame %&gt;% 
    rownames_to_column %&gt;% pivot_longer(-1) %&gt;% ggplot(aes(rowname, 
    name, fill = value)) + geom_tile() + geom_text(aes(label = round(value, 
    2))) + xlab(&quot;&quot;) + ylab(&quot;&quot;) + coord_fixed() + scale_fill_gradient2(low = &quot;purple&quot;, 
    mid = &quot;violet&quot;, high = &quot;white&quot;)</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-5-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>alldata4 %&gt;% select_if(is.numeric) %&gt;% cor %&gt;% as.data.frame %&gt;% 
    rownames_to_column %&gt;% pivot_longer(-1) %&gt;% ggplot(aes(rowname, 
    name, fill = value)) + geom_tile() + geom_text(aes(label = round(value, 
    2))) + xlab(&quot;&quot;) + ylab(&quot;&quot;) + coord_fixed() + scale_fill_gradient2(low = &quot;red&quot;, 
    mid = &quot;pink&quot;, high = &quot;white&quot;)</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-5-2.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>alldata4 %&gt;% select(NAME, Assault, Murder, RM_Rate, UrbanPop, 
    Rape) %&gt;% arrange(desc(Murder)) %&gt;% na.omit() %&gt;% slice(1:25) %&gt;% 
    ggplot(aes(x = Rape, y = Assault, color = Murder)) + geom_smooth(method = &quot;lm&quot;) + 
    geom_point(size = 2) + ggtitle(&quot;Assaults vs. Rape Plot in States with a Top 25 Murder Rate&quot;) + 
    ylab(&quot;# of Assaults per 100,000 people&quot;) + xlab(&quot;# of Rapes per 100,000 people&quot;) + 
    theme_minimal() + scale_y_continuous(lim = c(0, 350), breaks = seq(0, 
    350, 50)) + scale_x_continuous(lim = c(15, 50), breaks = seq(15, 
    50, 5)) + scale_color_gradient(low = &quot;blue&quot;, high = &quot;red&quot;)</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-5-3.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>alldata2 %&gt;% arrange(desc(Murder)) %&gt;% slice(1:10, 91:100) %&gt;% 
    ggplot(aes(x = reorder(NAME, Value), y = Value, fill = Murder)) + 
    geom_bar(stat = &quot;summary&quot;, fun = mean) + geom_errorbar(stat = &quot;summary&quot;, 
    fun.data = mean_se) + ggtitle(&quot;Mean Value (Income/Rent) by States Top 5 and Bottom 5 in Murder Rate&quot;) + 
    ylab(&quot;Mean Value&quot;) + xlab(&quot;States&quot;) + coord_flip()</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-5-4.png" width="672" style="display: block; margin: auto;" /></p>
<p><em>In the first correlation matrix this specific matrix was looking at the Income to murder rate correlation values. In the second correlation matrix this specific matrices was looking at the Rent to murder rate correlation values. In both matrices, murder and assault both shared a strong positive correlation with one another (r = 0.8). I thought that the Urban population size percentage would also be positively correlated with the murder rate but this was not the case - in fact there was almost no correlation between the two (r = 0.07). The Income to murder rate was most negatively correlated with murder (r = -0.68) - meaning that as the Median income increased the murder rate decreased. The Rent to murder rate was also most negatively correlated with murder (r = -0.74). Lastly, there was no correlation between the murder rate and median rent (r = 0.01), however there was a weak negative correlation between the murder rate and income (r = -0.41).</em></p>
<p><em>In my first graph, I plotted the # of Assaults per 100,000 people and the # of rapes per 100,000 people in states who had a murder rate in the top 25. I wanted to see if there was any sort of correlation between the three variables - given that they are all negative outcomes. From what I could discern from the graph, there was a slight positive correlation between Assaults and Rapes when looking at states with a top 25 murder rate. States with high murder rates (&gt; However, there states with higher assault rates had higher murder rates, which from the correlation matrix supports the data. </em></p>
<p><em>Lastly, I wanted to look at how the averaged values (Income/rent) differed across states who were top 5 and bottom 5 in murder rates. According to the barplot there does not appear to be any significant difference between the averaged values - given that the error bars overlap. However, the majority of states with a higher murder rate were more likely to have a lower Value than states with a low murder rate. The mean overall values were not much different from one another. Furthermore, Maine had a lower mean value than Georgia yet Georgia has a very high murder rate while Maine has one of the lowest. There could be many reasons for this difference such as more job opportunities in Georgia than Maine or a larger population - thus having a greater chance of having a high murder rate.</em></p>
</div>
<div id="dimensionality-reduction-30-pts" class="section level4">
<h4>5. Dimensionality Reduction (30 pts)</h4>
<ul>
<li><p>Either k-means/PAM clustering or PCA (inclusive “or”) should be performed on at least three of your variables (3 is just the minimum: using more/all of them will make this much more interesting!)</p>
<ul>
<li>All relevant steps discussed in class (e.g., picking number of PCs/clusters)</li>
<li>A visualization of the clusters or the first few principal components (using ggplot2)</li>
<li>Supporting paragraph or two describing results found, interpreting the clusters/PCs in terms of the original variables and observations, discussing goodness of fit or variance explained, etc.</li>
</ul></li>
</ul>
<pre class="r"><code>library(cluster)

sub2 &lt;- alldata4 %&gt;% select(Murder, Rape, Assault)

vec &lt;- vector()

for (i in 1:10) {
    sub3 &lt;- sub2 %&gt;% select(Murder, Rape, Assault) %&gt;% kmeans(i)
    vec[i] &lt;- sub3$tot.withinss
}
ggplot() + geom_line(aes(x = 1:10, y = vec)) + scale_x_continuous(name = &quot;k&quot;, 
    breaks = 1:10)</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-6-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>gower1 &lt;- daisy(sub2, metric = &quot;gower&quot;)
pam1 &lt;- pam(gower1, k = 1, diss = T)
plot(pam1, which = 1)</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-6-2.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>sub4 &lt;- alldata3 %&gt;% select(Murder, Rape, Assault, UrbanPop, 
    Value)

sub4 = data.frame(scale(sub4))

ggplot(sub4, aes(x = Value, y = Murder)) + geom_point() + coord_fixed()</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-6-3.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>eig1 &lt;- sub4 %&gt;% select(Murder, Value) %&gt;% cor %&gt;% eigen()
eig1</code></pre>
<pre><code>## eigen() decomposition
## $values
## [1] 1.4122814 0.5877186
## 
## $vectors
##            [,1]       [,2]
## [1,] -0.7071068 -0.7071068
## [2,]  0.7071068 -0.7071068</code></pre>
<pre class="r"><code>eig1$vectors</code></pre>
<pre><code>##            [,1]       [,2]
## [1,] -0.7071068 -0.7071068
## [2,]  0.7071068 -0.7071068</code></pre>
<pre class="r"><code>sub4_matrix &lt;- sub4 %&gt;% select(Murder, Value) %&gt;% as.matrix
sub4_scores &lt;- t(t(eig1$vectors) %*% t(sub4_matrix)) %&gt;% as.data.frame

sub4_scores %&gt;% ggplot(aes(V1, V2)) + geom_point(size = 2)</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-6-4.png" width="672" style="display: block; margin: auto;" /></p>
<p><em>For my first dimensionality reduction I wanted to look at the kmeans cluster of three variables - Murder, Assault, and Rape. In order to determine the number of clusters that would work best for this data set and that was determined to be k = 1. From what I could discern from the first kmeans cluster - both principle components (PC1 and PC2) accounted for 50.38% of the variability found in the data set - which is rather impressive. Furthermore, there was only one cluster found. This is not surprising given that it was hard to group by states given their was only one observation per state. Nevertheless, there was not a very high goodness of fit given that there was not much clustering found in the dataset.</em></p>
<p><em>Lastly, I wanted to look at the PCA analysis between murder and value. I wanted to see if there was any underlying variance between these two variables that could explain variations in my data set. I obtained the proper eig%vector and eig%values for the data set. When analyzing the principle components there appeart to be a very weak negative corrlation between the two principle componets. States with high V1 scores generally have lower murder rates while states with low V1 scores have higher murder rates. This correlation is still very weak, however there does appear to be some relationship between the two variables.</em>
#### 6. Neatness, Holistic/Discretionary Points (5 pts)</p>
<ul>
<li>Keep things looking nice! Your project should not knit to more than 30 or so pages (probably closer to 10-20)! You will lose points if you print out your entire dataset(s), have terrible formatting, etc. If you start your project in a fresh .Rmd file, you are advised to copy set-up code below and include it: this will do things like automatically truncate if you accidentally print out a huge dataset, etc. Imagine this is a polished report you are giving to your PI or boss to summarize your work researching a topic.</li>
</ul>
<pre class="r"><code>## paste this chunk into the ```{r setup} chunk at the top of
## your project 1 .Rmd file

knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = &quot;center&quot;, 
    warning = F, message = F, tidy = TRUE, tidy.opts = list(width.cutoff = 60), 
    R.options = list(max.print = 100))</code></pre>
</div>
</div>
<div id="where-do-i-find-data" class="section level3">
<h3>Where do I find data?</h3>
<p>OK, brace yourself!</p>
<p>You can choose ANY datasets you want that meet the above criteria for variables and observations. I’m just sitting here but off the top of my head, if you are into amusement parks, you could look at amusement-park variables, including ticket sales per day etc.; then you could join this by date in weather data. If you are interested in Game of Thrones, you could look at how the frequency of mentions of character names (plus other character variables) and the frequency of baby names in the USA…You could even take your old Biostats data and merge in new data (e.g., based on a Google forms timestamp).</p>
<p>You could engage in some “me-search”: You can <a href="https://support.spotify.com/ca-en/article/data-rights-and-privacy-settings/">request your Spotify data</a> or <a href="https://help.netflix.com/en/node/101917">download Netflix viewing activity</a>, Amazon purchase history, etc. You can use your Google Fit/Fitbit/Apple watch data, etc. These can be combined (e.g., with each other, with other data sources).</p>
<p>You can make it as serious as you want, or not, but keep in mind that you will be incorporating this project into a portfolio webpage for your final in this course, so choose something that really reflects who you are, or something that you feel will advance you in the direction you hope to move career-wise, or something that you think is really neat. On the flip side, regardless of what you pick, you will be performing all the same tasks, so it doesn’t end up being that big of a deal.</p>
<p>If you are totally clueless and have no direction at all, log into the server and type</p>
<pre class="r"><code>data(package = .packages(all.available = TRUE))</code></pre>
<p>This will print out a list of <strong>ALL datasets in ALL packages</strong> installed on the server (a ton)! Scroll until your eyes bleed! Actually, do not scroll that much… To start with something more manageable, just run the command on your own computer, or just run <code>data()</code> to bring up the datasets in your current environment. To read more about a dataset, do <code>?packagename::datasetname</code>.</p>
<p>If it is easier for you, and in case you don’t have many packages installed, a list of R datasets from a few common packages (also downloadable in CSV format) is given at the following website: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a> (including types/numbers of variables in each)</p>
<ul>
<li><p>A good package to download for fun/relevant data is <code>fivethiryeight</code>. Just run <code>install.packages("fivethirtyeight"), load the packages with</code>library(fivethirtyeight)<code>, run</code>data()`, and then scroll down to view the datasets. Here is an online list of all 127 datasets (with links to the 538 articles). Lots of sports, politics, current events, etc: <a href="https://cran.r-project.org/web/packages/fivethirtyeight/vignettes/fivethirtyeight.html" class="uri">https://cran.r-project.org/web/packages/fivethirtyeight/vignettes/fivethirtyeight.html</a></p></li>
<li><p>If you have already started to specialize (e.g., ecology, epidemiology) you might look at discipline-specific R packages (vegan, epi, respectively). We will be using some tools from these packages later in the course, but they come with lots of data too, which you can explore according to the directions above</p></li>
<li><p>However, you <em>emphatically DO NOT</em> have to use datasets available via R packages! In fact, I would much prefer it if you found the data from completely separate sources and brought them together (a much more realistic experience in the real world)! You can even reuse data from your SDS328M project, provided it shares a variable in common with other data which allows you to merge the two together (e.g., if you still had the timestamp, you could look up the weather that day: <a href="https://www.wunderground.com/history/" class="uri">https://www.wunderground.com/history/</a>). If you work in a research lab or have access to old data, you could potentially merge it with new data from your lab!</p></li>
<li><p>Here is a curated list of interesting datasets (read-only spreadsheet format): <a href="https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit" class="uri">https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit</a></p></li>
<li><p>Here is another great compilation of datasets: <a href="https://github.com/rfordatascience/tidytuesday" class="uri">https://github.com/rfordatascience/tidytuesday</a></p></li>
<li><p>Here is the UCI Machine Learning Repository: <a href="https://archive.ics.uci.edu/ml/index.php" class="uri">https://archive.ics.uci.edu/ml/index.php</a></p>
<ul>
<li>See also <a href="https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data" class="uri">https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data</a></li>
</ul></li>
<li><p>Here is another good general place to look: <a href="https://www.kaggle.com/datasets" class="uri">https://www.kaggle.com/datasets</a></p></li>
<li><p>To help narrow your search down or to see interesting variable ideas, check out <a href="https://www.tylervigen.com/spurious-correlations" class="uri">https://www.tylervigen.com/spurious-correlations</a>. This is the spurious correlations website, and it is fun, but if you look at the bottom of each plot you will see sources for the data. This is a good place to find very general data (or at least get a sense of where you can scrape data together from)!</p></li>
<li><p>If you are interested in medical data, check out www.countyhealthrankings.org</p></li>
<li><p>If you are interested in scraping UT data, the university makes <em>loads</em> of data public (e.g., beyond just professor CVs and syllabi). Check out all the data that is available in the statistical handbooks: <a href="https://reports.utexas.edu/statistical-handbook" class="uri">https://reports.utexas.edu/statistical-handbook</a></p></li>
</ul>
<div id="broader-data-sources" class="section level5">
<h5>Broader data sources:</h5>
<p><a href="www.data.gov">Data.gov</a> 186,000+ datasets!</p>
<p><a href="Social%20Explorer">Social Explorer</a> is a nice interface to Census and American Community Survey data (more user-friendly than the government sites). May need to sign up for a free trial.</p>
<p><a href="www.bls.gov">U.S. Bureau of Labor Statistics</a></p>
<p><a href="www.census.gov">U.S. Census Bureau</a></p>
<p><a href="www.gapminder.org/data">Gapminder</a>, data about the world.</p>
<p>…</p>
</div>
</div>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
